# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 04:29
from __future__ import unicode_literals

import Core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'text'), ('video', 'video'), ('audio', 'audio'), ('roller', 'roller')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tree', models.CharField(max_length=100)),
                ('house', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_date', models.CharField(blank=True, max_length=100, null=True)),
                ('run_date', models.CharField(blank=True, max_length=100, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('wright', models.CharField(blank=True, max_length=100, null=True)),
                ('binder', models.FileField(blank=True, help_text='PDF', null=True, upload_to=Core.models.binderUpload_handler)),
                ('binder_img', models.FileField(blank=True, null=True, upload_to=Core.models.binderImgUpload_handler)),
                ('stgd', models.FileField(blank=True, null=True, upload_to=Core.models.stgdUpload_handler)),
                ('stgd_img', models.FileField(blank=True, null=True, upload_to=Core.models.stgdImgUpload_handler)),
                ('splash', models.ImageField(blank=True, null=True, upload_to=Core.models.splashUpload_handler)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='Core.Show'),
        ),
    ]
