# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-20 22:35
from __future__ import unicode_literals

import Core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Core.models.image_upload_handler)),
            ],
        ),
        migrations.CreateModel(
            name='MiscFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Core.models.misc_upload_handler)),
            ],
        ),
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Core.models.pdf_upload_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tree', models.CharField(max_length=100)),
                ('house', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_date', models.CharField(blank=True, max_length=100, null=True)),
                ('run_date', models.CharField(blank=True, max_length=100, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('wright', models.CharField(blank=True, max_length=100, null=True)),
                ('binder', models.FileField(blank=True, help_text='PDF', null=True, upload_to=Core.models.binderUpload_handler)),
                ('binder_img', models.FileField(blank=True, null=True, upload_to=Core.models.binderImgUpload_handler)),
                ('stgd', models.FileField(blank=True, null=True, upload_to=Core.models.stgdUpload_handler)),
                ('stgd_img', models.FileField(blank=True, null=True, upload_to=Core.models.stgdImgUpload_handler)),
                ('splash', models.FileField(blank=True, null=True, upload_to=Core.models.splashUpload_handler)),
            ],
        ),
        migrations.CreateModel(
            name='SoundFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Core.models.sound_upload_handler)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Show')),
            ],
        ),
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Core.models.text_upload_handler)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='Core.Show')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Core.models.video_upload_handler)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='Core.Show')),
            ],
        ),
        migrations.AddField(
            model_name='pdffile',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='Core.Show'),
        ),
        migrations.AddField(
            model_name='miscfile',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc', to='Core.Show'),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='Core.Show'),
        ),
    ]
