# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
