# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170711_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
