# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170711_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
